version: '3.8'

services:
  web:
    build: .
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__DefaultConnection=Data Source=/app/Data/GrupoCeleste.db
      - MercadoPago__AccessToken=${MERCADOPAGO_ACCESS_TOKEN}
      - MercadoPago__PublicKey=${MERCADOPAGO_PUBLIC_KEY}
    volumes:
      - ./Data:/app/Data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  default:
    name: grupoceleste-network